### ISSUE TITLE
The esp-modbus CPP wrapper

### ISSUE THREAD

**Issue by alisitsyn** [DomiMartinGlogi/DynamicModbusMaster#10]
This old project will probably help you.

https://github.com/alisitsyn/modbus_support/blob/mb_support/modbus_add_cpp_wrapper/

**Comment by dmglogowskiOS** [comment]
Thank you for the provided assistance but I already have mostly completed the related functions, Only really missing is Modbus-TCP which is planned for but I haven't had the time to work on it yet. 

(I also don't have any Modbus-TCP devices for testing yet...)
